name: Hola Mundo

on: [push]

jobs:
  primero:
    runs-on: ubuntu-latest
    steps:
      - name: Mensaje
        run: echo "Hola mundo!!!"
        
      - name: Touch file
        run: |
          touch hola.txt
          ls -al
          
      - name: Set text
        run: |
          echo "Hola mundo" >> hola.txt
          ls -al
          
      - name: Read file
        run: |
          cat hola.txt

  segundo:
    runs-on: ubuntu-latest
    needs: [primero]
    steps:
      - name: Directorio
        run: ls -al
